#!/bin/bash
echo '

 __   __   __   __             __  ___                 ___  __  
/  \ |  \ /  \ /  \    | |\ | /__`  |   /\  |    |    |__  |__) 
\__/ |__/ \__/ \__/    | | \| .__/  |  /~~\ |___ |___ |___ |  \ 
                                                                

By ALmohawis'
echo ' Which Odoo Version Install :
[1] Odoo 19 [1]
[2] Odoo 18 [2]
'
read -p "====> " V

if [ "$V" = "1" ]; then
    echo 'Version 19?
[1] Yes [1]
[2] No [2]
' 
    read -p "====>" S
    if [ "$S" == "1" ]; then
        echo "ok"
        chmod +x ./Scripts/odoo-19-installer.sh
        ./Scripts/odoo-19-installer.sh
    else
        echo "Cancel"
        exit
    fi
elif [ "$V" = "2" ]; then
    echo ' Version 18?
[1] Yes [1]
[2] No [2]
'
    read -p "====> " S
    if [ "$S" = "1" ]; then
        echo "ok"
        chmod +x ./Scripts/odoo-18-installer.sh
        ./Scripts/odoo-18-installer.sh
    else
        echo "Cancel"
        exit
    fi
else
    echo "NotFound / Exit Please Run ./setup-odoo Again"
fi

