#!/bin/bash
echo '

 __   __   __   __             __  ___                 ___  __  
/  \ |  \ /  \ /  \    | |\ | /__`  |   /\  |    |    |__  |__) 
\__/ |__/ \__/ \__/    | | \| .__/  |  /~~\ |___ |___ |___ |  \ 
                                                                

By ALmohawis'


# Version check
REQUIRED_VERSION="24.04"
CURRENT_VERSION=$(lsb_release -rs)

echo "Current Ubuntu version: $CURRENT_VERSION"
if [[ "$CURRENT_VERSION" != "$REQUIRED_VERSION" ]]; then
    echo "Warning: This script is intended for Ubuntu $REQUIRED_VERSION.
Press ENTER Or Any Key to continue at your own risk, or press X to cancel."

    read -n 1 CHOICE
    echo ""
    if [[ "$CHOICE" == "X" || "$CHOICE" == "x" ]]; then
        echo -e "\nAborted by user."
        exit 1
    fi
fi

echo "Continuing with the script..."

echo ' Which Odoo Version Install :
[1] Odoo 19 [1]
[2] Odoo 18 [2]
'
read -n 1 -p "====> " V
echo ""
if [ "$V" = "1" ]; then
    echo 'Version 19?
[1] Yes [1]
[2] No [2]
' 
    read -n 1 -p "====>" S
    echo ""
    if [ "$S" == "1" ]; then
        echo "ok"
        chmod +x ./Scripts/odoo-19-installer.sh
        ./Scripts/odoo-19-installer.sh
    else
        echo "Cancel"
        exit
    fi
elif [ "$V" = "2" ]; then
    echo ' Version 18?
[1] Yes [1]
[2] No [2]
'
    read -n 1 -p "====> " S
    echo ""
    if [ "$S" = "1" ]; then
        echo "ok"
        chmod +x ./Scripts/odoo-18-installer.sh
        ./Scripts/odoo-18-installer.sh
    else
        echo "Cancel"
        exit
    fi
else
    echo "NotFound / Exit Please Run ./setup-odoo Again"
fi

